### ISSUE TITLE
安装了以后为啥用不了呀，webvpn页面左侧没有出现小箭头

### ISSUE THREAD

**Issue by bs6bs6** [kaaass/jlu-webvpn-assistant#1]
![image](https://user-images.githubusercontent.com/59904594/157599899-bf0e237b-51cf-4f7c-a5c9-228243191c9d.png)

**Comment by kaaass** [comment]
请检查下开发者工具（Ctrl+Shift+I进入）里是否有红色的报错信息，如果有的话麻烦复制一下或者截图。

**Comment by bs6bs6** [comment]
> 

![image](https://user-images.githubusercontent.com/59904594/157631565-a424937d-f932-49eb-a26c-4285b98f692c.png)

**Comment by kaaass** [comment]
OK，已经确认问题了。是脚本使用的 CDN BootCDN 部分地区无法访问，稍后发布版本修复。

**Comment by kaaass** [comment]
已经在新版本中修复，感谢报告～
