### ISSUE TITLE
tampermonkey.js中webvpn应变更为vpn

### ISSUE THREAD

**Issue by Reinhardt-L** [kaaass/jlu-webvpn-assistant#4]
![image](https://user-images.githubusercontent.com/65754243/190629305-4c780759-133c-45f1-b985-c840eac362f9.png)
WEBVPN系统已经将网址改为vpn.jlu.edu.cn
本来想直接pr merge想想算了没必要嗯水（）就删几个字母的事

**Comment by kaaass** [comment]
好家伙，竟然又改回去了……

感谢报告，已经在 2979b8a 修复。
