### ISSUE TITLE
使用该插件跳转其他网页失败

### ISSUE THREAD

**Issue by Reinhardt-L** [kaaass/jlu-webvpn-assistant#5]
是用的是release中的1.1.2，手动将匹配改成了当前用的vpn.jlu.edu.cn，但仍跳转失败。怀疑是vpn更改了跳转域名的加密，可否尝试维护一下？本人技术实在有限，参不透（难顶）

**Comment by kaaass** [comment]
可否提供一些 URL 样本？目前我已经毕业了，维护存在一些困难

**Comment by Reinhardt-L** [comment]
啊原来这样，主要是我没学过相关东西然后也没看懂他用的什么加解密（）太抽象了

在vpn中打开知网 cnki.net
先跳转
"https://vpn.jlu.edu.cn/http/44696469646131313237446964696461a976f7614dc6ae03/?wrdrecordvisit=1685951692000"
然后跳转到
"https://vpn.jlu.edu.cn/https/44696469646131313237446964696461bd6feb2600c6a01e8255e278/"

打开新教务管理系统 iedu.jlu.edu.cn
先跳转
"https://vpn.jlu.edu.cn/https/44696469646131313237446964696461a37df87d4dc2a702825ee37999669b/?wrdrecordvisit=1685951887000"
然后跳转到
"https://vpn.jlu.edu.cn/https/44696469646131313237446964696461a979ef2609c4be59c95ff222d46b/tpass/login?service=https%3A%2F%2Fiedu.jlu.edu.cn%2Fjwapp%2Fsys%2Femaphome%2Fportal%2Findex.do"

打开网络自助服务 ip.jlu.edu.cn
先跳转
"https://vpn.jlu.edu.cn/https/44696469646131313237446964696461a368b2620fdde512c84ea96fd9/pay?wrdrecordvisit=1685952014000"
然后跳转到
"https://vpn.jlu.edu.cn/https/44696469646131313237446964696461a368b2620fdde512c84ea96fd9/pay/"

**Comment by kaaass** [comment]
此 Issue 已在 #6 中得到解决，稍后将更新版本

**Comment by Reinhardt-L** [comment]
帅，不过其实想了解一下他的原理，可否讲解一下（）

**Comment by kaaass** [comment]
你的分析是正确的，的确是 webvpn 系统换了一套新的 key 与 iv
