### ISSUE TITLE
同学你好，最近各类网址都无法进入并且报错：PARSE_FAILED，请问是什么原因（以选课系统为例）

### ISSUE THREAD

**Issue by lsqm01** [kaaass/jlu-webvpn-assistant#7]
![图片](https://github.com/kaaass/jlu-webvpn-assistant/assets/99775911/1455e971-da5c-4826-aa6c-f2553036c5d6)

**Comment by kaaass** [comment]
应该和 #5 是同样的问题，应该已经被 #6 修复了。我刚刚更新了下版本，升级后应该就可以了。
